# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 465e5f3f8b5640418ff60b34e2745a1c25c784cd7d87f8d02cefce0b6be63c7897e18ecb57c5e9f7255ac950ef16f1c89e5b43e1ac22cd49eb53932519ba189f

test:
  secret_key_base: 7e714c7ce8cb46ac3bea52bb6dbb5dc54fcdf6fa7cc332688729773f726a5e33aebbe5d020e0156b82b4b6182ca3c7cca8ea8909acc970a4b581b589e05bc541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
